project_id = "ysqnwkysszqjwvnuqruk"

[functions.elevenlabs-signed-url]
verify_jwt = false

[functions.elevenlabs-tts]
verify_jwt = false

[functions.migrate-external-user]
verify_jwt = false

[functions.create-mollie-subscription]
verify_jwt = false

[functions.update-trial-days]
verify_jwt = false

[functions.update-mollie-subscription]
verify_jwt = false

[functions.track-voice-usage]
verify_jwt = false

[functions.check-subscription-status]
verify_jwt = false

[functions.get-usage-status]
verify_jwt = false
